
import React, { useState, useCallback } from 'react';
import { generateJavaSolution } from './services/geminiService';
import { Button } from './components/Button';
import { Card } from './components/Card';
import { CodeBlock } from './components/CodeBlock';
import { LoadingSpinner } from './components/LoadingSpinner';
import { JavaIcon } from './components/icons/JavaIcon';
import { SparklesIcon } from './components/icons/SparklesIcon';

const App: React.FC = () => {
  const [solution, setSolution] = useState<{ javaCode: string; explanation: string } | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const problemDescription = `Tienes una lista de 4 trabajadores con los siguientes datos: el nombre, el apellido, el documento, el salario y un bono base con el mismo valor para cada trabajador lo que significa que este valor no se pide, se almacena en un atributo de la persona. Lo que debes hacer es modificar el bono según el salario de cada trabajador, estos salarios son distintos, los que ganen menos de un salario mínimo aumentar 100.000 pesos al bono y los que ganen mas aumentar 50.000 pesos.`;

  const handleGenerateSolution = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    setSolution(null);
    try {
      const result = await generateJavaSolution(problemDescription);
      setSolution(result);
    } catch (err) {
      setError('Failed to generate solution. Please ensure your API key is configured correctly.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  }, [problemDescription]);

  return (
    <div className="min-h-screen bg-slate-900 text-slate-200 font-sans p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto">
        
        <header className="text-center mb-8">
          <div className="flex justify-center items-center gap-4">
            <JavaIcon className="h-12 w-12 text-orange-400" />
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-red-500">
              Solucionador de Ejercicios Java POO
            </h1>
          </div>
          <p className="mt-4 text-lg text-slate-400">
            Genera código Java y explicaciones de conceptos de POO usando IA.
          </p>
        </header>

        <main>
          <Card>
            <h2 className="text-2xl font-semibold mb-4 text-sky-400">Enunciado del Problema</h2>
            <p className="text-slate-300 leading-relaxed">{problemDescription}</p>
          </Card>
          
          <div className="text-center my-8">
            <Button onClick={handleGenerateSolution} disabled={isLoading}>
              {isLoading ? (
                <>
                  <LoadingSpinner />
                  Generando Solución...
                </>
              ) : (
                <>
                  <SparklesIcon className="w-5 h-5 mr-2"/>
                  Generar Solución con IA
                </>
              )}
            </Button>
          </div>

          {error && (
            <Card>
              <h3 className="text-xl font-semibold text-red-500">Error</h3>
              <p className="text-red-400 mt-2">{error}</p>
            </Card>
          )}

          {solution && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
              <Card>
                <h3 className="text-2xl font-semibold mb-4 text-green-400">Código de la Solución en Java</h3>
                <CodeBlock code={solution.javaCode} language="java" />
              </Card>
              <Card>
                <h3 className="text-2xl font-semibold mb-4 text-purple-400">Explicación de Conceptos POO</h3>
                <div 
                  className="prose prose-invert prose-p:text-slate-300 prose-headings:text-slate-100 prose-strong:text-sky-400"
                  dangerouslySetInnerHTML={{ __html: solution.explanation.replace(/\n/g, '<br />') }}
                />
              </Card>
            </div>
          )}
        </main>

        <footer className="text-center mt-12 text-slate-500 text-sm">
          <p>Powered by Google Gemini API. Generated by a world-class senior frontend React engineer.</p>
        </footer>

      </div>
    </div>
  );
};

export default App;
